using BMPTrains_2020.DomainCode;
using System;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace BMPTrains_2020
{
    public partial class frmReport : Form
    {
        public frmReport()
        {
            InitializeComponent();
        }

        //public frmReport(string text, string reportHeader = "", string pageHeader = "")
        //{
        //    InitializeComponent();
        //    string s = "";
        //    if (reportHeader == "")
        //    { 
        //        s += "<div style=' font-size: 1.2em '>Project: " + Globals.Project.ProjectName + "</div><br/>";
        //        s += "<div style=' font-size: 1.2em'>Date: " + DateTime.Now.ToString("MM/dd/yyyy") + "</div><br/>";
        //    }

        //    s += text;
        //    wbReport.DocumentText = s;

        //    if (pageHeader != "")
        //    {
        //        this.Text = pageHeader;
        //    }
        //}

        public frmReport(string text, string reportHeader = "", string pageHeader = "")
        {
            InitializeComponent();

            // Build attractive header (project / file / date / user)
            string projectName = System.Security.SecurityElement.Escape(Globals.Project?.ProjectName ?? "");
            string fileNameRaw = Globals.Project?.FileName ?? "";
            string fileName = string.IsNullOrWhiteSpace(fileNameRaw) ? "" : System.IO.Path.GetFileName(fileNameRaw);
            string date = DateTime.Now.ToString("MM/dd/yyyy");
            string generatedBy = Globals.IsValidatedUser ? System.Security.SecurityElement.Escape(Globals.UserEmail) : "Unregistered User";

            var headerCss = new StringBuilder();
            headerCss.AppendLine("<style>");
            headerCss.AppendLine(".report-header { border:1px solid #dbe9f7; background: linear-gradient(#f7fbff,#eaf6ff); padding:12px; border-radius:6px; display:flex; justify-content:space-between; align-items:center; margin-bottom:12px; font-family: Arial, sans-serif; }");
            headerCss.AppendLine(".report-left { max-width:70%; }");
            headerCss.AppendLine(".report-title { font-size:1.25em; font-weight:700; color:#0b5394; }");
            headerCss.AppendLine(".report-sub { font-size:0.95em; color:#23475a; margin-top:4px; }");
            headerCss.AppendLine(".report-meta { text-align:right; font-size:0.95em; color:#333; }");
            headerCss.AppendLine(".report-meta div { margin-bottom:4px; }");
            headerCss.AppendLine(".report-body { font-family: Arial, sans-serif; font-size: 13px; color:#222; }");
            headerCss.AppendLine("</style>");

            string headerHtml;
            if (string.IsNullOrWhiteSpace(reportHeader))
            {
                // default header layout
                var left = new StringBuilder();
                left.AppendLine($"<div class='report-left'>");
                left.AppendLine($"  <div class='report-title'>Project: {projectName}</div>");
                if (!string.IsNullOrWhiteSpace(fileName))
                    left.AppendLine($"  <div class='report-sub'>File: {System.Security.SecurityElement.Escape(fileName)}</div>");
                left.AppendLine("</div>");

                var right = new StringBuilder();
                right.AppendLine("<div class='report-meta'>");
                right.AppendLine($"  <div><strong>Date:</strong> {date}</div>");
                right.AppendLine($"  <div><strong>Generated by:</strong> {generatedBy}</div>");
                right.AppendLine("</div>");

                headerHtml = $"<div class='report-header'>{left}{right}</div>";
            }
            else
            {
                // Use provided reportHeader (assumed already formatted), but wrap with styling so visuals remain consistent.
                headerHtml = $"<div class='report-header'>{reportHeader}</div>";
            }

            // Compose full HTML document for the WebBrowser control
            string html = "<html><head><meta http-equiv='X-UA-Compatible' content='IE=Edge'></head><body>";
            html += headerCss.ToString();
            html += headerHtml;
            html += $"<div class='report-body'>{text}</div>";
            html += "</body></html>";

            wbReport.DocumentText = html;

            if (!string.IsNullOrWhiteSpace(pageHeader))
            {
                this.Text = pageHeader;
            }
        }

        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            this.Close();
            
        }

        private void printToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (!Globals.IsValidatedUser)
            {
                ShowRegistrationRequired();
                return;
            }

            wbReport.Print();
        }

        private void saveToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (!Globals.IsValidatedUser)
            {
                ShowRegistrationRequired();
                return;
            }

            Save();
        }

        private void menuStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void wbReport_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
        {

        }
        public void Save()
        {
            SaveFileDialog savefile = new SaveFileDialog();
            // set a default file name

            savefile.InitialDirectory = Common.WorkingDirectory();

            savefile.FileName = "report.html";
            // set filters - this can be done in properties as well
            savefile.Filter = "HTML files (*.html)|*.html|All files (*.*)|*.*";

            if (savefile.ShowDialog() == DialogResult.OK)
            {
                System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.WaitCursor;
                if (saveToFile(savefile.FileName))
                {
                    System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.Default;
                    MessageBox.Show("File " + savefile.FileName + " Saved Successfully");
                }
                else
                {
                    System.Windows.Forms.Cursor.Current = System.Windows.Forms.Cursors.Default;
                    MessageBox.Show("File " + savefile.FileName + " Error occurred in save");
                }
            }
        }
        public bool saveToFile(string filename)
        {            
            try
            {
                using (StreamWriter sw = new StreamWriter(filename))
                    sw.WriteLine(wbReport.Document.Body.Parent.OuterHtml);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private void helpToolStripMenuItem_Click(object sender, EventArgs e)
        {
            BMPTrainsProject.OpenWebsite();
        }

        private void frmReport_Resize(object sender, EventArgs e)
        {
            wbReport.Width = this.Width - 20;
            wbReport.Height = this.Height - 60;
        }

        private void copyToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (!Globals.IsValidatedUser)
            {
                ShowRegistrationRequired();
                return;
            }

            this.wbReport.Document.ExecCommand("Copy", false, null);
        }

        private void copyToolStripMenuItem_Click_1(object sender, EventArgs e)
        {
            if (!Globals.IsValidatedUser)
            {
                ShowRegistrationRequired();
                return;
            }

            this.wbReport.Document.Focus();
            SendKeys.SendWait("^a");
            SendKeys.SendWait("^a^c");
            DialogResult dialogResult = MessageBox.Show("Report has been copied to the clipboard as HTML text", "Copy Report", MessageBoxButtons.OK);
        }

        public void setURL(string url)
        {
            wbReport.Navigate(url);
        }

        private void frmReport_Load(object sender, EventArgs e)
        {

        }

        // Helper to inform unregistered users
        private void ShowRegistrationRequired()
        {
            string msg = $"These features are only available to registered users. Visit {BMPTrainsProject.URL_Website} for more information";
            MessageBox.Show(msg, "Registered Users Only", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
    }
}
